### ISSUE TITLE
Regression bug: toWebGL() doesn't show points in RStudio Viewer on Windows

### ISSUE THREAD

**Issue by daattali** [plotly/plotly.R#1214]
This was introduced some time between 2018-01-26 to 2018-03-07

```
toWebGL(plot_ly(iris, x = ~Sepal.Width, y = ~Sepal.Length))
```

In RStudio on Windows, the plot shows up empty

(originally reported in #1211)

**Comment by cpsievert** [comment]
Do you see any console errors similar to this? -- https://github.com/plotly/plotly.js/issues/2457

**Comment by daattali** [comment]
Yes - 
![image](https://user-images.githubusercontent.com/952340/37164348-00444632-22c8-11e8-9b34-1b3d5fbca08d.png)

**Comment by cpsievert** [comment]
I believe this is fixed now, please re-open if not @daattali

**Comment by daattali** [comment]
@cpsievert I just installed plotly from github and I still have the same issue, with the same javascript console error (I don't have the power to open the issue)

**Comment by cpsievert** [comment]
@daattali what version of RStudio are you running? The new preview release changed rendering engines (it's now based on chromium) which might fix a lot of the issues you're experiencing

**Comment by daattali** [comment]
I just downloaded today's preview v1.2.679 and I still do not see any points in rstudio

![image](https://user-images.githubusercontent.com/952340/41077245-884994f8-69e3-11e8-8766-579074ed37a4.png)

**Comment by cpsievert** [comment]
Ok, I was able to reproduce this on Win-7. This is only an issue for you in RStudio, right? I can open in IE11 and it renders.
